sudo: true
dist: trusty
language: clojure
notifications:
  email:
cache:
  directories:
  - "$HOME/.m2"
before_install:
- curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
script: ./scripts/test-all.sh
