sudo: true
dist: trusty
language: clojure
notifications:
  email:
    - antonin@hildebrand.cz
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - yes y | sudo lein upgrade
  - curl -sSL https://raw.githubusercontent.com/cljs-oss/canary/master/scripts/install-canary.sh | bash
  - cd test; npm install
script:
  - ./scripts/test-all.sh
